learning_log/learning_logs/urls.py
"""Define os padrões de url para learning logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #pagina inicial
    path('',views.index,name='index'),
    #Pagina que mostra todos os tópicos
    path('topics/',views.topics,name='topics'),
    #Pagina de detalhes para um único tópico
    path('topics/<int:topic_id>/',views.topic,name='topic')
]

learning_log/ll_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls'))
]

learning_log/learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """Um tópico que o usuário está aprendendo"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Retorna uma representação de string do modelo"""
        return self.text

class Entry(models.Model):
    """Algo específico aprendido sobre um tópico"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Retorna uma string simples representando a entrada"""
        return f'{self.text[:50]}...'

learning_log/learning_logs/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.
def index(request):
    """A página inicial para registro de aprendizagem"""
    return render(request,'learning_logs/index.html')
 
def topics(request):
    """Mostra todos os tópicos"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)

def topic(request,topic_id):
    """Mostra um único tópico e todas as suas entradas"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

learning_log/learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning log</a> - 
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Learning log helps you keep track of your learning, for any topic you're interested in.</p>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{%extends 'learning_logs/base.html'%}

{%block content%}

<p>Topic: {{topic.text}}</p>

<p>Entries:</p>

<ul>
    {%for entry in entries%}
        <li>
            <p>{{entry.date_added|date:'d M, Y H:i'}}</p>
            <p>{{entry.text|linebreaks}}</p>
        </li>
    {%empty%}
        <li>There no entries for this topic yet.</li>
    {%endfor%}
</ul>

{%endblock content%}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topics</p>

<ul>
    {%for topic in topics%}
        <li>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>
        </li>
    {%empty%}
        <li>No topics have been added yet.</li>
    {%endfor%}
    </ul>


{% endblock content %}